//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebpackAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talleres
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string PathImage { get; set; }
        public string Description { get; set; }
        public string URLYoutubeLive { get; set; }
        public string Speaker { get; set; }
        public string TwitterSpeaker { get; set; }
    }
}
